apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pacman    
  name: pacman-crb-wcm
subjects:
- kind: ServiceAccount
  name: pacman-sa
  namespace: pacman-wcm
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
spec: {}
