apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman-deploy
    app: pacman
  name: pacman-deploy
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman-deploy
  template:
    metadata:
      labels:
        name: pacman-deploy
    spec:
      serviceAccount: pacman-sa
      containers:
      - image: docker.io/rfontain/pacman:v1
        imagePullPolicy: IfNotPresent
        name: pacman-container
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_AUTH_USER 
          value: admin      
        - name: MONGO_AUTH_PWD
          valueFrom:
            secretKeyRef:
              name: pacman-secret
              key: MONGO_SERVICE_HOST         
        - name: MONGO_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_SERVICE_HOST              
        - name: MONGO_REPLICA_SET
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_REPLICA_SET
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_DATABASE
        - name: MY_MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_PORT
        - name: MONGO_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_USE_SSL
        - name: MONGO_VALIDATE_SSL
          valueFrom:
            configMapKeyRef:
              name: pacman-config
              key: MONGO_VALIDATE_SSL
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        #rouge
        - name: COLOR
          value: "rgb(197, 33, 33)"
        #bleue
          #value: "rgb(59, 108, 170)"
        - name: MY_IMAGE
          value: RED HAT
        - name: MESSAGE
          value: "Initial Version"

