apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: pacman    
  name: pacman-ingress
  namespace: pacmangit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/server-alias: "ocpaws.pacman.dev-adv.net, aks.pacman.dev-adv.net"
spec:
  rules:
  - host: pacman.dev-adv.net
    http:
      paths:
      - path: /
        backend:
          serviceName: pacman-svc
          servicePort: 80

          



